// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RG390AGz8-CgI--V36EajzrQGgiVD64',
    appId: '1:674750679479:web:39ce2d7154b6873fe78032',
    messagingSenderId: '674750679479',
    projectId: 'flutternexora',
    authDomain: 'flutternexora.firebaseapp.com',
    storageBucket: 'flutternexora.firebasestorage.app',
    measurementId: 'G-3FVW57M3QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE1VwSIoYwyJdW0r7xkIaPKn2JhQ9i0rQ',
    appId: '1:674750679479:android:e75cb4ca38d4bc58e78032',
    messagingSenderId: '674750679479',
    projectId: 'flutternexora',
    storageBucket: 'flutternexora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjVPnl3G0oY_Fym-QznRh6hTa-9foUi8',
    appId: '1:674750679479:ios:77fb743eaf6dce4ee78032',
    messagingSenderId: '674750679479',
    projectId: 'flutternexora',
    storageBucket: 'flutternexora.firebasestorage.app',
    iosBundleId: 'com.example.startapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjVPnl3G0oY_Fym-QznRh6hTa-9foUi8',
    appId: '1:674750679479:ios:77fb743eaf6dce4ee78032',
    messagingSenderId: '674750679479',
    projectId: 'flutternexora',
    storageBucket: 'flutternexora.firebasestorage.app',
    iosBundleId: 'com.example.startapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3RG390AGz8-CgI--V36EajzrQGgiVD64',
    appId: '1:674750679479:web:8b39521f49c0ce48e78032',
    messagingSenderId: '674750679479',
    projectId: 'flutternexora',
    authDomain: 'flutternexora.firebaseapp.com',
    storageBucket: 'flutternexora.firebasestorage.app',
    measurementId: 'G-GL4WM923B7',
  );
}
